# Generated by Django 4.2.1 on 2023-06-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_ordine_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='visibile',
            field=models.BooleanField(default=True),
        ),
    ]
