# Generated by Django 4.2.1 on 2023-06-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_prodotto_visibile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='cvvCarta',
            field=models.CharField(default='000', max_length=3),
        ),
        migrations.AddField(
            model_name='ordine',
            name='numeroCarta',
            field=models.CharField(default='0000000000000000', max_length=16),
        ),
        migrations.AddField(
            model_name='ordine',
            name='scadenzaCarta',
            field=models.DateField(default='2021-01-01', max_length=5),
        ),
    ]
