# Generated by Django 4.2.1 on 2023-06-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='categoria',
            field=models.CharField(default='Non specificato', max_length=200),
        ),
    ]
