# Generated by Django 4.2.1 on 2023-06-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_prodotto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodotto',
            name='categoria',
        ),
    ]
