# Generated by Django 4.2.1 on 2023-06-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_prodotto_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddField(
            model_name='prodotto',
            name='categoria',
            field=models.CharField(default='Non specificato', max_length=200),
        ),
    ]
